### ISSUE TITLE
undefined local variable or method `token', `issue_add_with_telegram'

### ISSUE THREAD

**Issue by pavel-redkin** [massdest/redmine_telegram_email#1]
Completed 500 Internal Server Error in 301ms (ActiveRecord: 10.6ms)

NameError (undefined local variable or method `token' for #<Mailer:0x002b24dba98cd0>):
  plugins/redmine_telegram_email/lib/telegram_mailer_patch.rb

```
        if telegram_chat_id != 0
          Mailer.speak(msg, telegram_chat_id, attachment, token)

        end

```

**Comment by massdest** [comment]
Thank you for report. Now it should work.
