### ISSUE TITLE
Не работает.

### ISSUE THREAD

**Issue by chmelov** [massdest/redmine_telegram_email#11]
Попытались установить плагин на Redmine в контейнере:
Environment:
  Redmine version                4.2.0.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux-gnu]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.13.0
  Mercurial                      5.3.1
  Cvs                            1.12.13
  Bazaar                         3.0.2
  Git                            2.31.1
  Filesystem                     
Redmine plugins:
  easy_gantt                     1.12
  easy_mindmup                   1.0
  easy_wbs                       1.5
  redmine_agile                  1.6.0
  redmine_checklists             3.1.18
  redmine_omniauth_google        0.0.1

При вводе команды:
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
получаем ошибку:
Exception `ActiveSupport::EncryptedFile::MissingContentError' at /home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/encrypted_file.rb:44 - Missing encrypted content file in /home/redmine/redmine/config/credentials.yml.enc.

Однако после всего этого Redmine запускается и модуть видится. Вбиваем все настройки, добавляем поля. При создании новой задачи бот молчит. Кнопка "Отключить оповещение по email" тоже не работает.

**Comment by aekondratiev** [comment]
ошибка не влияет на работу
убедитесь в my/account
что заполнен Telegram Channel
и НЕ стоит галка "Не извещать об изменениях, которые я сделал сам"

**Comment by chmelov** [comment]
Проверили все неоднократно. Конечно Telegram Channel заполнен: ID специально созданного канала. Задачи создавали друг другу. Оповещение по email приходит. Телеграмбот молчит.
Сам по себе телеграмбот проверяли. От него приходит сообщение в канал из командной строки баша.
Возможно ли какое-то ограничение из-за того, что Redmine запущен в контейнере? 
Поля в модуле отличаются от тех, что в инструкции.
![Screenshot_20211006_153126](https://user-images.githubusercontent.com/92030695/136202939-fd7cba75-d293-439a-8d1d-93dca40eb3da.png)

**Comment by aekondratiev** [comment]
поля такие должны быть

Telegram Channel
Telegram disable email

про контейнер не знаю, у меня в виртаулках все
