### ISSUE TITLE
Messages not sent

### ISSUE THREAD

**Issue by Egregius** [massdest/redmine_telegram_email#2]
Hi,

I'd like to use this plugin. If I understand correctly updates to issues are sent to Telegram instead of mail wich would be great as I am a huge Telegram fan. 
Weither or not I place a check on the disable mail checkbox the mail is sent, but not the telegram.
When I use the redmine_telegram_global plugin messages arrive, but I think this plugin could be better as users can set their own chat id. 

Thanks in advance for your response.

**Comment by massdest** [comment]
Hello, yes - you understood correctly, each user can use telegram instead email or use both. I will check today later.

**Comment by massdest** [comment]
Ok, I added option to settings **Dont send to Telegram when user is author of issue or comment** - please test it, when you uncheck it - you should receive messages anyway. 

https://github.com/massdest/redmine_telegram_email/blob/master/images/redmine_telegram_email_settings.png

**Comment by Egregius** [comment]
Awesome! Thanks for the superfast respone!
Works as expected now 👍 

A small question, nothing to do with this issue. 
Is there a check in the reply of Telegram? 
I use the Telegram bot quite often in various application and found that they sometimes refuse the message. In my own PHP based scripts I run it in a loop until "result=OK" is returned by Telegram.

**Comment by massdest** [comment]
You are welcome, yes I thinking about it, but was to lazy to implement, however just some lines of code and some tests :) maybe do in this week.

**Comment by Egregius** [comment]
Great! Thank you!
I'll post another request in a new issue.
